name: release

on:
  push:
    tags:
      - '*'

jobs:

  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: npm install
      - name: package
        run: npm run electron-build
      - name: clean
        run: npx rimraf "dist/!(*.exe|*.deb|*.AppImage|*.dmg)"
      - name: upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ matrix.os }}
          path: dist
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/**"
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
